### ISSUE TITLE
How to print the tags.

### ISSUE THREAD

**Issue by Mikor-mkr** [UMich-BipedLab/LiDARTag#12]
Hello,

thanks for taking the time to check out my post. I want some help for printing the targets, more specifically is unclear to me how to generate those tags. Please, can you provide some information on that? I see that you provide some information about the targets at the lib folder but it is unclear tome how to use it. Also, I understand that I need to have matlab installed in order to print custom tags, is that right?

Thanks in advance!

**Comment by brucejk** [comment]
Hi, 

Thank you for being interested in this package! I will try my best to help. I would like to clarify the question. 

1. When you said "generate those tags", do you mean you want to use a different type of fiducial marker (not using ApriltagTag) for LiDARTag?
2. When you said "print custom tags", do you mean you need to regenerate the function library for the new fiducial markers for the LiDARTag?
3. Specifically, are you asking about [Building Your Own Customized Markers](https://github.com/UMich-BipedLab/LiDARTag#building-your-own-customized-markers)?

**Comment by brucejk** [comment]
I am going to close this issue due to inactivity. Please feel free to reopen if you have similar questions.

**Comment by mmalmeid** [comment]
Since I have been through the same issue, here is how I generated pdf's of appropriate size fiducials in the family `16h06`.
Just download the `resize-tags.sh` script from [this link](https://docs.cbteeple.com/robot/april-tags), and place it in `LiDARTag/matlab/function_dictionary`. Then update the configs of the script following the instructions in the link above, and you should have pdf's and png's with the for the `16h06` with the appropriate sizes
