### ISSUE TITLE
Limitations of tag extraction method

### ISSUE THREAD

**Issue by plumewind** [UMich-BipedLab/LiDARTag#4]
hello，

I test the lidartag in  a corridor, the tag is placed in the center, but the extracted cluster often contains points on the wall, like the picture (I displayed the clusters one by one).

![2020-04-27 23-40-31屏幕截图](https://user-images.githubusercontent.com/25976399/80391989-1e901680-88e1-11ea-9c05-f1f41d5705ef.png)

how to change some paramters?

I think the _updateCluster function, will make a cluster bigger and biger in a bad trend，I want to improve it, have you some advice?

Thanks a lot!

**Comment by brucejk** [comment]
I would be happy to help! 

First of all, it would be better if you place the tag around ![45 ^\circ](https://render.githubusercontent.com/render/math?math=45%20%5E%5Ccirc), even though it is not relevant to the problem.

Secondly, I have not tested the package in a narrow aisle; I tested in a clustered laboratory. However, it is indeed a scenario that we should consider and the package should also be able to handle. What is the distance from the wall to the tag and the size of the tag? 

Thirdly, if you could upload the bagfile to a google drive folder, I can further look into this and get back to you asap! You can [email](brucejkh@gmail.com) the link to me if you like!

Lastly, this is an on-going project and we are currently improving the clustering algorithm to make it more robust. Please bear with us!

**Comment by brucejk** [comment]
I would be happy to help! 

First of all, it would be better if you place the tag around ![45 ^\circ](https://render.githubusercontent.com/render/math?math=45%20%5E%5Ccirc), even though it is not relevant to the problem.

Secondly, I have not tested the package in a narrow aisle; I tested in a clustered laboratory. However, it is indeed a scenario that we should consider and the package should also be able to handle.  I noticed there are only two rings on the wall got included. What is the distance from the wall to the tag and the size of the tag?

Thirdly, if you could upload the bagfile to a google drive folder, I can further look into this and get back to you asap! You can [email](brucejkh@gmail.com) the link to me if you like!

Lastly, this is an on-going project and we are currently improving the clustering algorithm to make it more robust. Please bare with us!

**Comment by plumewind** [comment]
Sorry, I can not send my data to you because of the wall.

But I find a big problem, I carefully considered the idea of cluster expansion algorithm. I found that the tag plane must be parallel to the lidar coordinate system yoz plane, so that the generation of clusters is reasonable. However, if it is not, there will be a big problem in this cluster generation.

**Comment by brucejk** [comment]
It is okay that you can't share the data; I will still try to help based on what you described.

Could you illustrate more on ' the tag plane must be parallel to the lidar coordinate system yoz plane'? The cluster algorithm works fine even if the tag does not being vertical to the ground plane (x-y plane, as z-axis pointing up to the air). Could you tell me what the tag size is and what the distance from the wall to the tag?

**Comment by plumewind** [comment]
hello，a pcd is ok？

[small-lidartag.zip](https://github.com/UMich-BipedLab/LiDARTag/files/4543512/small-lidartag.zip)

the tag is 16h11, size about 0.3*0.3, but no rings , I add a function:

[lidar_param.zip](https://github.com/UMich-BipedLab/LiDARTag/files/4543526/lidar_param.zip)

**Comment by plumewind** [comment]
hello,

I make a rosbag for lidartag, about 2.7s .(too big to send successfully)

[lidar_1smalltag_rosbag.zip](https://github.com/UMich-BipedLab/LiDARTag/files/4544383/lidar_1smalltag_rosbag.zip)

Thanks a lot.

**Comment by brucejk** [comment]
Hi, 

I have discussed it with my labmate. We found several issues. 

1. The ring number labeling process is not robust. For example,
18 index:177 x: 2.60129 y: -2.81091 z: -0.0231521
18 index:178 x: 2.58906 y: -2.81539 z: -0.0231215
18 index:198 x: 2.40824 y: -2.97797 z: -0.0231521
18 index:199 x: 2.402 y: -2.98942 z: -0.0231826
18 index:1809 x: 2.58659 y: -2.80341 z: -0.0441436
18 index:1810 x: 2.58115 y: -2.81521 z: -0.0442021
18 index:1830 x: 2.39094 y: -2.96561 z: -0.0440851
18 index:1831 x: 2.38786 y: -2.98092 z: -0.0442021
These points are labeled as ring 18 according to the rslidar32_addRing function. However, we can tell by the z-axis that they do not belong to the same ring. This causes a lot of issues for the following clustering algorithm because we heavily rely on the correctness of ring number.

2. The reason why some part of the wall is included is related to the labeling process. In the case of ring 18, these points actually contain all the points from this ring and the adjacent ring. All the points indexed between 177 and 1831 are included in the cluster.

Please let me know if you have other questions!

**Comment by brucejk** [comment]
Hi, 

I have discussed it with my labmate. We concluded that you might need to make the labeling process more robust.  For example,
18 index:177 x: 2.60129 y: -2.81091 z: -0.0231521
18 index:178 x: 2.58906 y: -2.81539 z: -0.0231215
18 index:198 x: 2.40824 y: -2.97797 z: -0.0231521
18 index:199 x: 2.402 y: -2.98942 z: -0.0231826
18 index:1809 x: 2.58659 y: -2.80341 z: -0.0441436
18 index:1810 x: 2.58115 y: -2.81521 z: -0.0442021
18 index:1830 x: 2.39094 y: -2.96561 z: -0.0440851
18 index:1831 x: 2.38786 y: -2.98092 z: -0.0442021
These points are labeled as ring 18 according to the rslidar32_addRing function. However, we can tell by the z-axis that they do not belong to the same ring. This causes a lot of issues for the following clustering algorithm because we heavily rely on the correctness of the ring number.

The reason why some part of the wall is included is related to the labeling process. In the case of ring 18, these points actually contain all the points from this ring and the adjacent ring. All the points indexed between 177 and 1831 are included in the cluster.

Please let me know if you have other questions!

**Comment by plumewind** [comment]
Thanks a lot !

I will check it right now.
